### ISSUE TITLE
Geoserver or mapserver is usting??

### ISSUE THREAD

**Issue by GISman-Lee** [mapcentia/dockerfiles#7]
Hi guys,

I just have a silly question. Actually is MapCentia using GeoServer or MapServer ? as I notice that in the docker file it's geoserver instead of mapserver >??

**Comment by mapcentia** [comment]
MapCentia GC2 is using MapServer and/or QGIS server as render backend. The Geoserver image is not used in a standard install. Here is a Docker compose file: https://github.com/mapcentia/dockerfiles/tree/master/docker-compose/gc2
